import com.google.api.client.auth.oauth2.Credential;
import com.google.api.client.extensions.java6.auth.oauth2.AuthorizationCodeInstalledApp;
import com.google.api.client.extensions.jetty.auth.oauth2.LocalServerReceiver;
import com.google.api.client.googleapis.auth.oauth2.GoogleClientSecrets;
import com.google.api.client.googleapis.auth.oauth2.GoogleAuthorizationCodeFlow;
import com.google.api.client.googleapis.javanet.GoogleNetHttpTransport;
import com.google.api.client.json.gson.GsonFactory;
import com.google.api.client.util.DateTime;
import com.google.api.client.util.store.FileDataStoreFactory;
import com.google.api.services.calendar.Calendar;
import com.google.api.services.calendar.CalendarScopes;
import com.google.api.services.calendar.model.*;

import java.io.*;
import java.security.GeneralSecurityException;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;

public class CalendarReminder {
    // 1. UPDATE THESE EMAILS
    private static final String TEACHER_EMAIL = "ragadijavi@gmail.com";
    private static final String YOUR_EMAIL = "neenustephen@gmail.com";

    private static final String APPLICATION_NAME = "Google Calendar Automation 2026";
    private static final GsonFactory JSON_FACTORY = GsonFactory.getDefaultInstance();
    private static final List<String> SCOPES = Collections.singletonList(CalendarScopes.CALENDAR);
    private static final String CREDENTIALS_FILE_PATH = "credentials.json";

    public static void main(String... args) throws IOException, GeneralSecurityException {
        final com.google.api.client.http.HttpTransport HTTP_TRANSPORT = GoogleNetHttpTransport.newTrustedTransport();

        // Load credentials file
        InputStream in = CalendarReminder.class.getResourceAsStream(CREDENTIALS_FILE_PATH);
        if (in == null) {
            throw new FileNotFoundException("Resource not found: " + CREDENTIALS_FILE_PATH);
        }

        GoogleClientSecrets clientSecrets = GoogleClientSecrets.load(JSON_FACTORY, new InputStreamReader(in));

        // Setup the OAuth flow
        GoogleAuthorizationCodeFlow flow = new GoogleAuthorizationCodeFlow.Builder(
                HTTP_TRANSPORT, JSON_FACTORY, clientSecrets, SCOPES)
                .setDataStoreFactory(new FileDataStoreFactory(new File("tokens")))
                .setAccessType("offline")
                .build();

        // This will open your web browser for a one-time login
        Credential credential = new AuthorizationCodeInstalledApp(flow, new LocalServerReceiver()).authorize("user");

        // Connect to the Calendar service
        Calendar service = new Calendar.Builder(HTTP_TRANSPORT, JSON_FACTORY, credential)
                .setApplicationName(APPLICATION_NAME)
                .build();

        // Define the Reminder Event
        Event event = new Event()
                .setSummary("Weekly Check-in Reminder")
                .setDescription("Automated weekly reminder generated by Java program.");

        // Set Start Time (Example: Monday, Jan 12, 2026 at 9:00 AM)
        DateTime startDateTime = new DateTime("2026-01-09T10:00:00Z"); // Use UTC time
        event.setStart(new EventDateTime().setDateTime(startDateTime).setTimeZone("CST"));

        // End time (9:30 AM)
        DateTime endDateTime = new DateTime("2026-01-09T10:30:00Z");
        event.setEnd(new EventDateTime().setDateTime(endDateTime).setTimeZone("CST"));

        // RECURRENCE: Set to repeat every Monday
        event.setRecurrence(Arrays.asList("RRULE:FREQ=WEEKLY;BYDAY=MO"));

        // ADD ATTENDEES: Both you and your teacher
        EventAttendee[] attendees = new EventAttendee[] {
                new EventAttendee().setEmail(TEACHER_EMAIL),
                new EventAttendee().setEmail(YOUR_EMAIL),
        };
        event.setAttendees(Arrays.asList(attendees));

        // EXECUTE: Save the event and send email notifications automatically
        event = service.events().insert("primary", event)
                .setSendUpdates("all")
                .execute();

        System.out.printf("Success! Weekly event created: %s\n", event.getHtmlLink());
    }
}
